In [1]:
import pandas as pd
import numpy as np

# Part 1 - Data Import
Datum about hospital occupancy and tansportation modes in the Netherlands and Poland are imported and organized.
- Original global hospital occupancy data including country, date and hospital occupancy. Obtained from OWD: `https://ourworldindata.org/covid-hospitalizations`

- Original Netherlands tranport modes data including travel modes, region, date, population, periods. Obtained from CBS: `https://opendata.cbs.nl/statline/portal.html?_la=en&_catalog=CBS`

- Original Poland tranpsot modes data including travel modes and year. Obtained from SP: \
`https://stat.gov.pl/en/search/search.html`

Firstly, import hospital occupancy data.

In [2]:
# Import the file contians global daily hospital occupancy data, drop irrelevent data and only keep data of Netherlands and Poland 

file_path_h = '/Users/chenghuayang/Desktop/Q1/Python/TIL6010-Project/data/hopitality_2020-03_global.csv'
df = pd.read_csv(file_path_h, delimiter=',')
df.set_index('Code', inplace=True)

# Extract data of the Netherlands and poland respectively
df_nl = df[df['Entity'] == 'Netherlands']
df_pl = df[df['Entity'] == 'Poland']

# Create a new dataframe to integrate the data of two countries in the desired form
# Only keep rows with shared day values
df_h = pd.merge(df_nl, df_pl, on='Day')
df_h.set_index('Day', inplace=True)

# drop useless column
df_h = df_h.drop('Entity_x', axis=1)
df_h = df_h.drop('Entity_y', axis=1)

# rename column
df_h = df_h.rename({
            'Daily hospital occupancy_x': 'Netherlands Daily hospital occupancy',
            'Daily hospital occupancy_y': 'Poland Daily hospital occupancy'
        }, axis=1)
df_h

,Netherlands Daily hospital occupancy,Poland Daily hospital occupancy
Day,,
2020-04-08,2864,2425
2020-04-13,2415,2510
2020-04-15,2355,2499
2020-04-16,2377,2607
2020-04-17,2286,2673
...,...,...
2022-08-24,527,3025
2022-08-31,461,2507
2022-09-07,415,2102
2022-09-14,429,2487
2022-09-21,451,3086